'use strict';

// Output interesting anniversaries for today as text.

// Usage: node anniversary.js

const Util = require('../util/util.js');

class Anniversary {
    constructor (date = new Date()) {
        const today = date;

        // January -> 0, Dec -> 11
        this.month = today.getMonth();
        // 1 -> 1, 31 -> 31
        this.day = today.getDate();
    }

    info () {
        return {
            frenchRevolution: this.frenchRevolution(),
        };
    }

    // Numbered in terms of a leap year.
    // Jan 1 -> 0
    // Feb 29 -> 59
    // Mar 1 -> 60
    // Dec 31 -> 365
    dayOfYear () {
        const monthDays = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

        let dayNumber = this.day - 1;

        for (let m = 0; m < this.month; m++) {
            dayNumber += monthDays[m];
        }

        return dayNumber;
    }

    frenchRevolution () {
        const byDayNumber = [
            'Clay', // Corresponds to Jan 1 (winter).
            'Slate',
            'Sandstone',
            'Rabbit',
            'Flint',
            'Marl',
            'Limestone',
            'Marble',
            'Winnowing fan',
            'Gypsum',
            'Salt',
            'Iron',
            'Copper',
            'Cat',
            'Tin',
            'Lead',
            'Zinc',
            'Mercury',
            'Sieve',
            'Spurge-laurel',
            'Moss',
            'Butcher\'s Broom',
            'Snowdrop',
            'Bull',
            'Laurustinus',
            'Tinder polypore',
            'Daphne mezereum',
            'Poplar',
            'Axe',
            'Hellebore',
            'Broccoli',
            'Bay laurel',
            'Filbert',
            'Cow',
            'Box Tree',
            'Lichen',
            'Yew tree',
            'Lungwort',
            'Billhook',
            'Pennycress',
            'Rose Daphne',
            'Couch grass',
            'Common Knotgrass',
            'Hare',
            'Woad',
            'Hazel',
            'Cyclamen',
            'Celandine',
            'Sleigh',
            'Coltsfoot',
            'Dogwood',
            'Matthiola',
            'Privet',
            'Billygoat',
            'Wild Ginger',
            'Italian Buckthorn',
            'Violet',
            'Goat Willow',
            'Spade',
            'Leap Day', // Feb 29 in Gregorian. The French Revolutionary Calendar moved Leap Day to autumn.
            'Narcissus',
            'Elm',
            'Common fumitory',
            'Hedge mustard',
            'Goat',
            'Spinach',
            'Doronicum',
            'Pimpernel',
            'Chervil',
            'Twine',
            'Mandrake',
            'Parsley',
            'Scurvy-grass',
            'Daisy',
            'Tuna',
            'Dandelion',
            'Wood Anemone',
            'Maidenhair fern',
            'Ash tree',
            'Dibber',
            'Primrose',
            'Plane Tree',
            'Asparagus',
            'Tulip',
            'Hen',
            'Chard',
            'Birch',
            'Daffodil',
            'Alder',
            'Incubator',
            'Periwinkle',
            'Hornbeam',
            'Morel',
            'Beech Tree',
            'Bee',
            'Lettuce',
            'Larch',
            'Hemlock',
            'Radish',
            'Beehive',
            'Judas tree',
            'Romaine lettuce',
            'Horse chestnut',
            'Arugula or Rocket',
            'Pigeon',
            'Lilac',
            'Anemone',
            'Pansy',
            'Bilberry',
            'Grafting knife',
            'Rose',
            'Oak Tree',
            'Fern',
            'Hawthorn',
            'Nightingale',
            'Common Columbine',
            'Lily of the valley',
            'Button mushroom',
            'Hyacinth',
            'Rake',
            'Rhubarb',
            'Sainfoin',
            'Wallflower',
            'Fan Palm tree',
            'Silkworm',
            'Comfrey',
            'Salad burnet',
            'Basket of Gold',
            'Orache',
            'Weeding hoe',
            'Sea thrift',
            'Fritillary',
            'Borage',
            'Valerian',
            'Carp',
            'Euonymus',
            'Chives',
            'Bugloss',
            'White mustard',
            'Shepherd\'s crook',
            'Lucerne',
            'Daylily',
            'Clover',
            'Angelica',
            'Duck',
            'Lemon balm',
            'Oat grass',
            'Martagon lily',
            'Wild Thyme',
            'Scythe',
            'Strawberry',
            'Betony',
            'Pea',
            'Acacia',
            'Quail',
            'Carnation',
            'Elderberry',
            'Poppy plant',
            'Linden or Lime tree',
            'Pitchfork',
            'Cornflower',
            'Camomile',
            'Honeysuckle',
            'Bedstraw',
            'Tench',
            'Jasmine',
            'Vervain',
            'Thyme',
            'Peony',
            'Handcart',
            'Rye',
            'Oat',
            'Onion',
            'Speedwell',
            'Mule',
            'Rosemary',
            'Cucumber',
            'Shallot',
            'Wormwood',
            'Sickle',
            'Coriander',
            'Artichoke',
            'Clove',
            'Lavender',
            'Chamois',
            'Tobacco',
            'Redcurrant',
            'Hairy Vetchling',
            'Cherry',
            'Livestock pen',
            'Mint',
            'Cumin',
            'Bean',
            'Alkanet',
            'Guineafowl',
            'Sage',
            'Garlic',
            'Tare',
            'Wheat',
            'Shawm',
            'Spelt',
            'Common mullein',
            'Melon',
            'Ryegrass',
            'Ram',
            'Horsetail',
            'Mugwort',
            'Safflower',
            'Blackberry',
            'Watering can',
            'Foxtail millet',
            'Common Glasswort',
            'Apricot',
            'Basil',
            'Ewe',
            'Marshmallow',
            'Flax',
            'Almond',
            'Gentian',
            'Lock',
            'Carline thistle',
            'Caper',
            'Lentil',
            'Inula',
            'Otter',
            'Myrtle',
            'Rapeseed',
            'Lupin',
            'Cotton',
            'Mill',
            'Plum',
            'Millet',
            'Puffball',
            'Six-row Barley',
            'Salmon',
            'Tuberose',
            'Winter Barley',
            'Apocynum',
            'Liquorice',
            'Ladder',
            'Watermelon',
            'Fennel',
            'European Barberry',
            'Walnut',
            'Trout',
            'Lemon',
            'Teasel',
            'Buckthorn',
            'Mexican Marigold',
            'Harvesting basket',
            'Wild Rose',
            'Hazelnut',
            'Hops',
            'Sorghum',
            'Crayfish',
            'Bitter orange',
            'Goldenrod',
            'Maize or Corn',
            'Sweet Chestnut',
            'Pack Basket',
            'Virtue',
            'Talent',
            'Labor',
            'Opinions',
            'Awards',
            // They put Leap Day here, on Sept 22, but we're using a simplified conversion that ignores leap years.
            'Grape',
            'Saffron',
            'Chestnut',
            'Autumn Crocus',
            'Horse',
            'Impatiens',
            'Carrot',
            'Amaranth',
            'Parsnip',
            'Vat',
            'Potato',
            'Strawflower',
            'Winter squash',
            'Mignonette',
            'Donkey',
            'Four o\'clock flower',
            'Pumpkin',
            'Buckwheat',
            'Sunflower',
            'Wine-Press',
            'Hemp',
            'Peach',
            'Turnip',
            'Amaryllis',
            'Ox',
            'Eggplant',
            'Chili pepper',
            'Tomato',
            'Barley',
            'Barrel',
            'Apple',
            'Celery',
            'Pear',
            'Beetroot',
            'Goose',
            'Heliotrope',
            'Common fig',
            'Black Salsify',
            'Chequer Tree',
            'Plough',
            'Salsify',
            'Water caltrop',
            'Jerusalem artichoke',
            'Endive',
            'Turkey',
            'Skirret',
            'Watercress',
            'Leadworts',
            'Pomegranate',
            'Harrow',
            'Baccharis',
            'Azarole',
            'Madder',
            'Orange',
            'Pheasant',
            'Pistachio Nut',
            'Tuberous pea',
            'Quince',
            'Service tree',
            'Roller',
            'Rampion',
            'Cattle turnip',
            'Chicory',
            'Medlar',
            'Pig',
            'Lamb\'s lettuce',
            'Cauliflower',
            'Honey',
            'Juniper',
            'Pickaxe',
            'Wax',
            'Horseradish',
            'Cedar tree',
            'Fir',
            'Roe deer',
            'Gorse',
            'Cypress Tree',
            'Ivy',
            'Savin Juniper',
            'Fork hoe',
            'Sugar Maple',
            'Heather',
            'Reed plant',
            'Sorrel',
            'Cricket',
            'Pine nut',
            'Cork',
            'Truffle',
            'Olive',
            'Shovel',
            'Peat',
            'Coal',
            'Bitumen',
            'Sulphur',
            'Dog',
            'Lava',
            'Topsoil',
            'Manure',
            'Saltpeter',
            'Flail',
            'Granite' // Dec 31
        ];

        const topic = byDayNumber[ this.dayOfYear() ];

        return Util.capitalizedAllWords(topic);
    }

    static test () {
        console.log();

        const gen = new Anniversary();
        // LATER
    }

    static run () {
        const info = new Anniversary().info();

        Util.log(info);
    }
}

module.exports = Anniversary;

Anniversary.run();
