# Makes title bot post daily to Mastodon network.
name: Run Fediverse bots

on:
  schedule:
  - cron: '36 18 * * *'

jobs:
  fediverse:
    runs-on: ubuntu-latest
    steps:
    - name: Post titleGen note to Mastodon
      run: TITLE_BOT_TOKEN=${{ secrets.TITLE_BOT_TOKEN }} node titleGen/src/api/post.js
