# Makes title bot post daily to Mastodon network.
name: Run Fediverse bots

on:
  schedule:
  - cron: '36 18 * * *'

jobs:
  fediverse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
    
      - name: Post titleGen note to Mastodon
        run: |
          npm i
          TITLE_BOT_TOKEN=${{ secrets.TITLE_BOT_TOKEN }}
          node titleGen/src/api/post.js
