# Makes title bot post to Mastodon network.
name: Manually Run Fediverse bots

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Bot Name' # to be shown in the UI
        default: 'titleGen'
        required: false
        type: string

jobs:
  fediverse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
    
      - name: Post titleGen note to Mastodon
        env:
          TITLE_BOT_TOKEN: ${{ secrets.TITLE_BOT_TOKEN }}
        run: |
          npm i
          node titleGen/src/api/post.js
